### ISSUE TITLE
摘要功能在主题下无效

### ISSUE THREAD

**Issue by iamapig120** [dimpurr/Slackview#3]
当从原有旧的，包含摘要功能的主题更换时，摘要无法在主页显示，而是和WP默认一样显示文章全文

**Comment by AkatsukiRyuunosuke** [comment]
这个貌似本来就没有设计吧= =只能手动在文章中添加标签

**Comment by dimpurr** [comment]
这个的确不在考虑范围内 …… 设计就是为了首页大篇幅展示文章内容的，自行插入  就好了

**Comment by iamapig120** [comment]
已自行修改主题用于展示摘要……主要是摘要和内容文字不同……
