### ISSUE TITLE
sidebar相比single长时，点击回复导致排版错乱的问题

### ISSUE THREAD

**Issue by iamapig120** [dimpurr/Slackview#5]
![short](https://cloud.githubusercontent.com/assets/16359124/12004873/4dcb412c-abb9-11e5-822f-e8e28c2803a0.JPG)
当sidebar较长时，尝试点击回复，导致了整个页面排版错乱……
如截图所示。

**Comment by dimpurr** [comment]
问题已知，与 #1 重复了 …… 可能得等我闲下来才能修正吧
