### ISSUE TITLE
HTTPS支持性问题

### ISSUE THREAD

**Issue by BROBIRD** [dimpurr/Slackview#7]
HTTPS环境下，请求http://libs.baidu.com/jquery/2.0.0/jquery.min.js 是非HTTPS请求，默认会被浏览器拦截

**Comment by BROBIRD** [comment]
另外能否改成显示随机背景图……

**Comment by dimpurr** [comment]
随机背景图这个需求量还真是大啊 ……。 其实可以从我的 Adagiio 主题里直接拿代码。下次找个时间加上吧 (

<del>下次：大概暑假</del>

**Comment by BROBIRD** [comment]
加油……

**Comment by BROBIRD** [comment]
HTTPS bug fixed in #8
